language: node_js
node_js:
  - "0.8"
before_install:
  - gem --version
  - gem update --system
# jekyll stuff
  - gem install jekyll redcarpet
# compass & compass extensions
  - gem install compass modular-scale ceaser-easing compass-recipes
# grunt-webfont requirements
  - sudo apt-get install fontforge eot-utils
  - wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  - unzip woff-code-latest.zip -d sfnt2woff && cd sfnt2woff && make && sudo mv sfnt2woff /usr/local/bin/
# grunt
  - npm install -g grunt-cli
  - npm install
# bower
  - bower --version
  - bower -v install
script:
  - grunt test
