@@__warningComment__

dev: @@dev
version: "@@version"

url: "@@url"
name: "@@name"
description: "@@description"
permalink: "@@permalink"
baseurl: "@@baseurl"
baseurls: 
  scripts: "@@baseurls_scripts"
  styles: "@@baseurls_styles"
  images: "@@baseurls_images"
  fonts: "@@baseurls_fonts"

include: ['.htaccess']

markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

disqus_short_name: moox
#disqus_developer: true

google_analytics_tracking_id: UA-1716762-6
